package cmp320project;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author baraa
 */
public class AddEmployee extends javax.swing.JFrame {

    /**
     * Creates new form AddEmployee
     */
    myDBCon dbCon;
    ResultSet rs;
    EncryptionMD5 md5;

    public AddEmployee() {
        initComponents();
        this.setLocationRelativeTo(null); // center form in screen 
        
        // Initialize the database connection
        dbCon = new myDBCon();
        
        // Initializing MD5 Hasher
        md5 = new EncryptionMD5();
        
        // set all error labels to invisible
        lblUsernameError.setVisible(false);
        lblEmailError.setVisible(false);
        lblPasswordError.setVisible(false);
        lblConfirmPasswordError.setVisible(false);
        lblNameError.setVisible(false);
        
        // Populate employee types into the combo box
        cmbEmployeeType.addItem("Normal");
        cmbEmployeeType.addItem("Admin");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblPasswordError = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblNameError = new javax.swing.JLabel();
        lblEmailError = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ToggleConfirmPasswordBtn = new javax.swing.JToggleButton();
        txtPassword = new javax.swing.JPasswordField();
        txtEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnAddNewEmp = new javax.swing.JButton();
        TogglePasswordBtn = new javax.swing.JToggleButton();
        lblUsernameError = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtConfirmPassword = new javax.swing.JPasswordField();
        lblConfirmPasswordError = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbEmployeeType = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add New Employee");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Add New Employee Account");

        txtName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblPasswordError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblPasswordError.setForeground(new java.awt.Color(255, 0, 0));
        lblPasswordError.setText("error label");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Password:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Email:");

        lblNameError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblNameError.setForeground(new java.awt.Color(255, 0, 0));
        lblNameError.setText("error label");

        lblEmailError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblEmailError.setForeground(new java.awt.Color(255, 0, 0));
        lblEmailError.setText("error label");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Confirm Password:");

        ToggleConfirmPasswordBtn.setBackground(new java.awt.Color(255, 255, 255));
        ToggleConfirmPasswordBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cmp320project/SeePwdResized.png"))); // NOI18N
        ToggleConfirmPasswordBtn.setToolTipText("Show password");
        ToggleConfirmPasswordBtn.setMinimumSize(new java.awt.Dimension(522, 523));
        ToggleConfirmPasswordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleConfirmPasswordBtnActionPerformed(evt);
            }
        });

        txtPassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Type:");

        btnAddNewEmp.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnAddNewEmp.setText("Add New");
        btnAddNewEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewEmpActionPerformed(evt);
            }
        });

        TogglePasswordBtn.setBackground(new java.awt.Color(255, 255, 255));
        TogglePasswordBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cmp320project/SeePwdResized.png"))); // NOI18N
        TogglePasswordBtn.setToolTipText("Show password");
        TogglePasswordBtn.setMinimumSize(new java.awt.Dimension(522, 523));
        TogglePasswordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TogglePasswordBtnActionPerformed(evt);
            }
        });

        lblUsernameError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblUsernameError.setForeground(new java.awt.Color(255, 0, 0));
        lblUsernameError.setText("error label");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Name:");

        txtConfirmPassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        lblConfirmPasswordError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblConfirmPasswordError.setForeground(new java.awt.Color(255, 0, 0));
        lblConfirmPasswordError.setText("error label");

        txtUsername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Username:");

        cmbEmployeeType.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEmail)
                                    .addComponent(btnAddNewEmp)
                                    .addComponent(txtName)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TogglePasswordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ToggleConfirmPasswordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtUsername))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblConfirmPasswordError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblNameError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblUsernameError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPasswordError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblEmailError, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(cmbEmployeeType, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNameError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsernameError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblEmailError)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPasswordError, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TogglePasswordBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ToggleConfirmPasswordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblConfirmPasswordError)))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(cmbEmployeeType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddNewEmp)
                .addGap(0, 43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void clearErrorLabels() {
        // erase error label text and set visibility to false
        lblUsernameError.setText("");
        lblUsernameError.setVisible(false);
        lblPasswordError.setText("");
        lblPasswordError.setVisible(false);
        lblConfirmPasswordError.setText("");
        lblConfirmPasswordError.setVisible(false);
        lblNameError.setText("");
        lblNameError.setVisible(false);
        lblEmailError.setText("");
        lblEmailError.setVisible(false);
    }
    
    /**
    * Validates if the entered password and its confirmation match and are not empty.
    *
    * @return true if the password is valid, otherwise false.
    */
    boolean isValidPassword() {
       boolean result = true; 

       // Check if password is empty
       if (txtPassword.getText().trim().isEmpty()) {
           lblPasswordError.setText("Invalid. Cannot be empty.");
           lblPasswordError.setVisible(true);
           result = false;
       }

       // Check if confirmation matches the password
       if (!txtConfirmPassword.getText().trim().equals(txtPassword.getText().trim())) {
           lblConfirmPasswordError.setText("Invalid. Password does not match.");
           lblConfirmPasswordError.setVisible(true);
           result = false;
       }

       return result;
   }
    
    /**
    * Checks if a username already exists in the database.
    *
    * @param username The username to check for duplicates.
    * @return true if the username already exists, otherwise false.
    * @throws SQLException If there's an error executing the SQL query.
    */
    private boolean isDuplicate(String username) throws SQLException {
        String stmtSQL = "SELECT username FROM account WHERE username = '" + username.toLowerCase()+ "'";
        rs = dbCon.executeStatement(stmtSQL);

        if (rs.isBeforeFirst()) lblUsernameError.setText("Username already taken.");
        lblUsernameError.setVisible(true);
        
        // Check if the resultset has data which indicates a duplicate
        return rs.isBeforeFirst();
    }
    
    /**
    * Validates the data entered by the user.
    *
    * @return true if the entered data is valid, otherwise false.
    */
   boolean isValidData() {
       boolean result = true;

       // Check if name is empty or too long
       if (txtName.getText().trim().isEmpty() || (txtName.getText().trim().length() > 20)) {
           if (txtName.getText().trim().isEmpty()) {
               lblNameError.setText("Invalid. Cannot be empty.");
           } else if (txtName.getText().trim().length() > 20) {
               lblNameError.setText("Invalid. Must be < 21 chars.");
           }
           lblNameError.setVisible(true);
           result = false;
       }

       // Check if username is empty or too long
       if (txtUsername.getText().trim().isEmpty() || (txtUsername.getText().trim().length() > 30)) {
           if (txtUsername.getText().trim().isEmpty()) {
               lblUsernameError.setText("Invalid. Cannot be empty.");
           } else if (txtUsername.getText().trim().length() > 30) {
               lblUsernameError.setText("Invalid. Must be < 31 chars.");
           }
           lblUsernameError.setVisible(true);
           result = false;
       }
       
       // Check if email is too long
       if (txtEmail.getText().trim().length() > 30) {
           if (txtEmail.getText().trim().length() > 30) {
               lblUsernameError.setText("Invalid. Must be < 31 chars.");
           }
           lblEmailError.setVisible(true);
           result = false;
       }
       
       return result;
   }
   
    /**
    * Clears all the input fields and resets them to default values.
    */
   void clearInputBoxes() {
       txtName.setText("");
       txtUsername.setText("");
       txtPassword.setText("");
       txtConfirmPassword.setText("");
   }
   
   /**
    * Validates all the user input fields.
    *
    * @return true if all entered data is valid, otherwise false.
    */
   boolean isValidAll() {
       clearErrorLabels();
       boolean result = isValidData();

       // Ensure both data and password are valid
       return isValidPassword() && result;
   }
    
   /**
    * Handles the click event of the button used to add a new employee.
    *
    * @param evt The event object associated with the action.
    */
    private void ToggleConfirmPasswordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleConfirmPasswordBtnActionPerformed
        // Check if the toggle button is selected.
        if (ToggleConfirmPasswordBtn.isSelected())
        {
            // If the toggle button is selected, set the echo characters of the password and confirm password fields to 0.
            // This effectively makes the characters in these fields visible.
            txtConfirmPassword.setEchoChar((char)0);
        }
        else
        {
            // If the toggle button is not selected, set the echo characters of the password and confirm password fields to '•'.
            // This hides the characters in these fields, replacing them with '•' symbols.
            txtConfirmPassword.setEchoChar('•');
        }
    }//GEN-LAST:event_ToggleConfirmPasswordBtnActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnAddNewEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewEmpActionPerformed
        try {
            // Check if the entered data is valid and the username does not already exist in the database.
            if (isValidAll() && !isDuplicate(txtUsername.getText().trim())) {

                // Prepare SQL query to insert the new user into the database.
                // The password is hashed using the MD5 algorithm.
                String prepSQL = "INSERT INTO account (username, password, name, accounttype, email) VALUES ('"
                + txtUsername.getText().trim().toLowerCase() + "', "
                + "'" + md5.getMD5(txtPassword.getText().trim()) + "', "
                + "'" + txtName.getText().trim() + "', "
                + "'employee', "
                + "'" + txtEmail.getText().trim() + "')";
                
                String prepSQL2 = "INSERT INTO employee (username, employeeType) VALUES ('"
                + txtUsername.getText().trim().toLowerCase() + "', "
                + "'" + cmbEmployeeType.getSelectedItem().toString().toLowerCase() + "')";

                String prepSQL3 = "INSERT INTO administrator values ('" + txtUsername.getText().trim().toLowerCase() + "')";
                
                // Execute the prepared SQL statement.
                int result1 = dbCon.executePrepared(prepSQL);
                int result2 = dbCon.executePrepared(prepSQL2);
                if (cmbEmployeeType.getSelectedItem().toString().equalsIgnoreCase("admin")){
                    dbCon.executePrepared(prepSQL3);
                }

                // If the SQL statement executed successfully and a new user was added,
                // inform the user with a success message.
                if (result1 > 0 && result2 > 0) {
                    javax.swing.JLabel label = new javax.swing.JLabel("Registerd successfully.");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);

                    // Clear the input fields after successful insertion.
                    clearInputBoxes();
                    this.dispose();
                } // Handle other cases where the user was not added. This section can be expanded.

                rs.close();
            } else {
                // If there are validation errors, inform the user to fix them.
                // Otherwise, inform the user if the entered username already exists.
                if (!isDuplicate(txtUsername.getText().trim())) {
                    javax.swing.JLabel label = new javax.swing.JLabel("Please fix validation errors...");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);
                } else {
                    javax.swing.JLabel label = new javax.swing.JLabel("Username Already exists. Use a different username.");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (SQLException e) {
            // Handle any SQL exceptions and inform the user with an error message.
            JOptionPane.showMessageDialog(null, "Error registering new account.");
        }
    }//GEN-LAST:event_btnAddNewEmpActionPerformed

    private void TogglePasswordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TogglePasswordBtnActionPerformed

        // Check if the toggle button is selected.
        if (TogglePasswordBtn.isSelected())
        {
            // If the toggle button is selected, set the echo characters of the password and confirm password fields to 0.
            // This effectively makes the characters in these fields visible.
            txtPassword.setEchoChar((char)0);
        }
        else
        {
            // If the toggle button is not selected, set the echo characters of the password and confirm password fields to '•'.
            // This hides the characters in these fields, replacing them with '•' symbols.
            txtPassword.setEchoChar('•');
        }
    }//GEN-LAST:event_TogglePasswordBtnActionPerformed

    // verify valid entry of integer values
    public boolean isInteger(String s) {
        try {
            Integer.parseInt(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

    // verify valid entry of double values
    public boolean isDouble(String s) {
        try {
            Double.parseDouble(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }


   /**
    * Event handler for adding a new employee to the database.
    * If the entered details are valid and the employee number is unique,
    * a new record is added to the database.
    *
    * @param evt Action event triggered by the 'Add New Employee button.
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton ToggleConfirmPasswordBtn;
    private javax.swing.JToggleButton TogglePasswordBtn;
    private javax.swing.JButton btnAddNewEmp;
    private javax.swing.JComboBox<String> cmbEmployeeType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblConfirmPasswordError;
    private javax.swing.JLabel lblEmailError;
    private javax.swing.JLabel lblNameError;
    private javax.swing.JLabel lblPasswordError;
    private javax.swing.JLabel lblUsernameError;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
