package cmp320project;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.util.*;


/**
 *
 * @author baraa
 */
public class UpdateDeleteProduct extends javax.swing.JFrame {

    /**
     * Creates new form UpdateDeleteProduct
     */
    // Instance variables
    myDBCon dbCon;              // Database connection object
    ResultSet rs;               // Result set for account data
    ResultSet rsCheck1;          // Result Set for warehouse capacity data
    ResultSet rsCheck2;          // Result Set for warehouse capacity data
    LoginUser user;             // Stores currently logged in user
    int ogQuantity;             //stores original quantity
    int ogSize;                 // Stores original size
        
    public UpdateDeleteProduct(LoginUser _user) {
        // Initializes GUI components created using the form editor in NetBeans or similar IDE
        initComponents();
        
        // creating connection
        dbCon = new myDBCon();
        
        // Positions this JFrame to the center of the screen
        this.setLocationRelativeTo(null);
        
        // set all error labels to invisible
        lblIDError.setVisible(false);
        lblNameError.setVisible(false);
        lblPriceError.setVisible(false);
        lblSizeError.setVisible(false);
        lblQuantityError.setVisible(false);

        // Initialize the database connection
        dbCon = new myDBCon();
        
        // getting supplier
        user = _user;
        
        // Fetch and display new data from the database to populate the form
        getNewData();
    }
    
    // This method fetches and sets the data from the database to populate the form's fields
    private void getNewData() {

        try {
            // Query to fetch account details of employees
            rs = dbCon.executeStatement("SELECT product.productID, name, price, \"Size\", Quantity FROM product, supplies WHERE product.productID = supplies.productID AND username = '" + user.username + "' ORDER BY productID ASC ");
            
            // Moves the cursor of the result set to the first row and populates the form fields with data
            rs.beforeFirst();
            rs.first();
            populateFields();
        } catch (SQLException e) {
            // Display an error message in case of any SQL exceptions
            javax.swing.JLabel label = new javax.swing.JLabel("SQL Error - Display selected product.");
            label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
            JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        lblNameError = new javax.swing.JLabel();
        lblQuantityError = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lblIDError = new javax.swing.JLabel();
        lblSizeError = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSize = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblPriceError = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Quantity:");

        lblNameError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblNameError.setForeground(new java.awt.Color(255, 0, 0));
        lblNameError.setText("error label");

        lblQuantityError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblQuantityError.setForeground(new java.awt.Color(255, 0, 0));
        lblQuantityError.setText("error label");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Size:");

        txtQuantity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("ID:");

        lblIDError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblIDError.setForeground(new java.awt.Color(255, 0, 0));
        lblIDError.setText("error label");

        lblSizeError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblSizeError.setForeground(new java.awt.Color(255, 0, 0));
        lblSizeError.setText("error label");

        txtName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Name:");

        txtSize.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSizeActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Price:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Update/Delete Product");

        lblPriceError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblPriceError.setForeground(new java.awt.Color(255, 0, 0));
        lblPriceError.setText("error label");

        txtID.setEditable(false);
        txtID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtPrice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnNext.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnNext.setText("Next >>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnPrevious.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        btnPrevious.setText("<< Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtSize)
                    .addComponent(txtPrice)
                    .addComponent(txtID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(txtName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtQuantity))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblIDError, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                            .addComponent(lblNameError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSizeError, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPriceError, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQuantityError, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(7, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(166, 166, 166))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPrevious)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNext)
                .addGap(194, 194, 194))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIDError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNameError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPriceError)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblSizeError)
                    .addComponent(txtSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQuantityError)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnNext)
                    .addComponent(btnPrevious))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void populateFields() {
        try {
            // Setting form fields with the current row's data from the result set.
            txtID.setText(rs.getString("productID"));
            txtName.setText(rs.getString("Name"));
            txtPrice.setText(rs.getString("Price"));
            txtSize.setText(rs.getString("Size"));
            txtQuantity.setText(rs.getString("Quantity"));
            
            // setting original quantity and size
            ogQuantity = Integer.parseInt(txtQuantity.getText().trim());
            ogSize = Integer.parseInt(txtSize.getText().trim());
            
            // Update the navigation buttons' states.
            EnableDisableButtons();
        } catch (SQLException ex) {
            Logger.getLogger(UpdateDeleteEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    // This method moves the result set's cursor to the next record and populates the form fields.
    private void MoveNext() {
        try {
            if (!rs.isLast()) {
                rs.next(); 
                populateFields();
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpdateDeleteEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    // This method moves the result set's cursor to the previous record and populates the form fields.
    private void MovePrevious() {
        try {
            // TODO add your handling code here:
            if (!rs.isFirst()) {
                rs.previous();
                populateFields();
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpdateDeleteEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // This method updates the state of the navigation buttons based on the cursor's position in the result set.
    private void EnableDisableButtons() {
        try {
            // Disable the Previous button if we're at the first record.
            if (rs.isFirst()) {
                btnPrevious.setEnabled(false);
            } else {
                btnPrevious.setEnabled(true);
            }

            // Disable the Next button if we're at the last record.
            if (rs.isLast()) {
                btnNext.setEnabled(false);
            } else {
                btnNext.setEnabled(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpdateDeleteEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    void clearErrorLabels() {
        // erase error label text and set visibility to false
        lblIDError.setText("");
        lblIDError.setVisible(false);
        lblNameError.setText("");
        lblNameError.setVisible(false);
        lblPriceError.setText("");
        lblPriceError.setVisible(false);
        lblSizeError.setText("");
        lblSizeError.setVisible(false);
        lblQuantityError.setText("");
        lblQuantityError.setVisible(false);
    }
    
    /**
    * This method checks if the provided string can be parsed as an integer.
    * @param s The string to check.
    * @return true if the string can be parsed as an integer, false otherwise.
    */
   public boolean isInteger(String s) {
       try {
           Integer.parseInt(s);
           return true;
       } catch (NumberFormatException ex) {
           return false;
       }
   }

   /**
    * This method checks if the provided string can be parsed as a double.
    * @param s The string to check.
    * @return true if the string can be parsed as a double, false otherwise.
    */
   public boolean isDouble(String s) {
       try {
           Double.parseDouble(s);
           return true;
       } catch (NumberFormatException ex) {
           return false;
       }
   }
   
   private boolean isDuplicate(String ID) throws SQLException {
        String stmtSQL = "SELECT warehouseID FROM warehouse WHERE warehouseID = " + ID.trim();
        rs = dbCon.executeStatement(stmtSQL);

        // Check if the resultset has data which indicates a duplicate
        return rs.isBeforeFirst();
    }
   
   boolean isValidData() {
       boolean result = true;
       
       // clears error labels
       clearErrorLabels();

       // Check if username is empty or too long
       if (txtName.getText().trim().isEmpty() || (txtName.getText().trim().length() > 30)) {
           if (txtName.getText().trim().isEmpty()) {
               lblNameError.setText("Invalid. Cannot be empty.");
           } else if (txtName.getText().trim().length() > 30) {
               lblNameError.setText("Invalid. Must be < 31 chars.");
           }
           lblNameError.setVisible(true);
           result = false;
       }
       
       // Check if ID is empty or negative or not Int
       if (txtSize.getText().trim().isEmpty() || !isInteger(txtSize.getText().trim()) || Integer.parseInt(txtSize.getText().trim()) < 0 ) {
           if (txtSize.getText().trim().isEmpty()) {
               lblSizeError.setText("Invalid. Cannot be empty.");
           } else if (!isInteger(txtSize.getText().trim()) || Integer.parseInt(txtSize.getText().trim()) < 0) {
               lblSizeError.setText("Invalid. Must be a 5 digit positive number.");
           }
           lblSizeError.setVisible(true);
           result = false;
       }
       
       // Check if price is empty or out of range or not a number
       if (txtPrice.getText().trim().isEmpty() || !(isInteger(txtPrice.getText().trim()) || isDouble(txtPrice.getText().trim())) || (Double.parseDouble(txtPrice.getText().trim()) < 0 || Double.parseDouble(txtPrice.getText().trim()) > 999999999.99 )) {
           if (txtPrice.getText().trim().isEmpty()) {
               lblPriceError.setText("Invalid. Cannot be empty.");
           } else if (!(isInteger(txtPrice.getText().trim()) || isDouble(txtPrice.getText().trim()))) {
               lblPriceError.setText("Invalid. Must be a number.");
           } else if ((Double.parseDouble(txtPrice.getText().trim()) < 0 || Double.parseDouble(txtPrice.getText().trim()) > 999999999.99 )) {
               lblPriceError.setText("Invalid. Must be a positive number less then 1,000,000,000.");
           } 
           lblPriceError.setVisible(true);
           result = false;
       }
       
       // Check if ID is empty or negative or not Int
       if (txtQuantity.getText().trim().isEmpty() || !isInteger(txtQuantity.getText().trim()) || Integer.parseInt(txtQuantity.getText().trim()) < 0 ) {
           if (txtQuantity.getText().trim().isEmpty()) {
               lblQuantityError.setText("Invalid. Cannot be empty.");
           } else if (!isInteger(txtQuantity.getText().trim()) || Integer.parseInt(txtQuantity.getText().trim()) < 0) {
               lblQuantityError.setText("Invalid. Must be a 5 digit positive number.");
           }
           lblQuantityError.setVisible(true);
           result = false;
       }
       
       return result;
   }
    
    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityActionPerformed

    private void txtSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSizeActionPerformed

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // Prompt the user for confirmation before proceeding with the update.
        int returnValue = JOptionPane.showConfirmDialog(this, "Are you sure you want to update?", "Warning", JOptionPane.YES_NO_OPTION);
        if (returnValue != JOptionPane.YES_OPTION) {
            return;  // Exit the method if user selects "No"
        }

        try {
            // Validate all input fields and check for duplicate usernames.
            if (isValidData()) {
                // Prepare the SQL UPDATE statement.
                String prepSQL = "UPDATE product SET name = '" + txtName.getText().trim() +
                "', price = " + txtPrice.getText().trim() +
                ", \"Size\" = " + txtSize.getText().trim() +  
                " WHERE productID = " + txtID.getText().trim();

                // prepare to update quantity
                String prepSQL1 = "UPDATE supplies SET "
                + "quantity = " + txtQuantity.getText().trim().toLowerCase()
                + " WHERE productID = " + txtID.getText().trim() + " AND username = '" + user.username + "'";
                
                // prepare to update quantity
                String prepSQL2 = "UPDATE stores SET "
                + "quantity = " + txtQuantity.getText().trim().toLowerCase()
                + " WHERE productID = " + txtID.getText().trim();
                
                
                rsCheck1 = dbCon.executeStatement("SELECT SUM(\"Size\" * Quantity) AS UsedCapacity FROM stores S JOIN product P ON S.ProductID = P.ProductID WHERE WarehouseID = (select warehouseID from stores where productID = " + txtID.getText().trim() + ")");
                rsCheck2 = dbCon.executeStatement("SELECT Capacity FROM warehouse WHERE warehouseID = (select warehouseID from stores where productID = " + txtID.getText().trim() + ")");
                rsCheck1.next();
                rsCheck2.next();
                
                if (rsCheck1.getInt("UsedCapacity") - (ogQuantity * ogSize) + (Integer.parseInt(txtSize.getText().trim()) * Integer.parseInt(txtQuantity.getText().trim())) > rsCheck2.getInt("Capacity"))
                {
                    JOptionPane.showMessageDialog(null, "Insufficient space in the warehosue. Please try again later.");
                    return; //exiting function
                }

                // Execute the prepared SQL statement.
                int result = dbCon.executePrepared(prepSQL);
                int result1 = dbCon.executePrepared(prepSQL1);
                int result2 = dbCon.executePrepared(prepSQL2);
                
                // Check the result and provide appropriate feedback to the user.
                if (result > 0 && result1 > 0 && result2 > 0) {
                    javax.swing.JLabel label = new javax.swing.JLabel("Product " + txtID.getText().trim() + " updated successfully.");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                    getNewData();  // Refresh the data
                } else {
                    javax.swing.JLabel label = new javax.swing.JLabel("Product not updated. Please fix validation errors...");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);
                }

            } else {
                // If validation fails, inform the user about the validation errors.
                javax.swing.JLabel label = new javax.swing.JLabel("Please fix validation errors...");
                label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException e) {
            // Catch SQL exceptions and show an error message to the user.
            JOptionPane.showMessageDialog(null, "Error updating Product." + e.getMessage());
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        MoveNext();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        MovePrevious();
    }//GEN-LAST:event_btnPreviousActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblIDError;
    private javax.swing.JLabel lblNameError;
    private javax.swing.JLabel lblPriceError;
    private javax.swing.JLabel lblQuantityError;
    private javax.swing.JLabel lblSizeError;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSize;
    // End of variables declaration//GEN-END:variables
}
